Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -86,27 +86,27 @@ jobs:
     # to build your code.
     # ℹ️ Command-line programs to run using the OS shell.
     # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    - if: matrix.language == 'c-cpp'
-      name: Show environment details
-      run: |
-        echo "Listing available compilers:"
-        gcc --version || echo "GCC not found"
-        g++ --version || echo "G++ not found"
-        clang --version || echo "Clang not found"
+#    - if: matrix.language == 'c-cpp'
+#      name: Show environment details
+#      run: |
+#        echo "Listing available compilers:"
+#        gcc --version || echo "GCC not found"
+#        g++ --version || echo "G++ not found"
+#        clang --version || echo "Clang not found"
         
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y gcc g++ make cmake
     
-    - if: matrix.language == 'c-cpp'
-      name: Build C/C++ project
-      run: |
-        set -x
-        sudo apt-get update
-        sudo apt-get install -y build-essential cmake
-        cmake .
-        make
+#    - if: matrix.language == 'c-cpp'
+#      name: Build C/C++ project
+#      run: |
+#        set -x
+#        sudo apt-get update
+#        sudo apt-get install -y build-essential cmake
+#        cmake .
+#        make
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
